<template>
  <div class="ml-2 loadingio-spinner-dual-ring-dd50gr7pdkk" v-if="loading">
    <div class="ldio-08klbbtfwryj">
      <div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    loading: Boolean,
    default: false,
  },
};
</script>

<style type="text/css">
@keyframes ldio-08klbbtfwryj {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-08klbbtfwryj div {
  box-sizing: border-box !important;
}
.ldio-08klbbtfwryj > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #1d0e0b transparent #1d0e0b transparent;
  animation: ldio-08klbbtfwryj 1s linear infinite;
}
.ldio-08klbbtfwryj > div:nth-child(2) {
  border-color: transparent;
}
.ldio-08klbbtfwryj > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-08klbbtfwryj > div:nth-child(2) div:before,
.ldio-08klbbtfwryj > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #1d0e0b;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #1d0e0b;
}
.ldio-08klbbtfwryj > div:nth-child(2) div:after {
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #1d0e0b;
}
.loadingio-spinner-dual-ring-dd50gr7pdkk {
  width: 24px;
  height: 24px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-08klbbtfwryj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.24);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-08klbbtfwryj div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
